# Generated by Django 4.2 on 2025-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(blank=True, max_length=70),
            preserve_default=False,
        ),
    ]
