# Generated by Django 4.2 on 2025-03-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title_short',
        ),
    ]
